### ISSUE TITLE
Simplify project setup and layout

### ISSUE THREAD

**Issue by dstendardi** [snowplow/snowplow-java-tracker#115]
Hello Alexander !

I would like to contribute to the java tracker in order to fix a leak in http connection pool.
Setting up the project seems a bit tedious, and I wonder if I can refactor the module layout by merging snowplow-java-tracker-core and the root module.
Of course I will take care of backward compatiblity and not move any deprecated package.
Also this change would be in a separate pull request. 

Are you guys ok with this kind of contribution  ?

**Comment by alexanderdean** [comment]
Hi @dstendardi - yes that's fine. Please go ahead and merge the two! We are planning to split off the Java and Android Trackers for a while, so no need to keep maintaining core for now...

**Comment by alexanderdean** [comment]
Closing as we can now track this via: #116
