### ISSUE TITLE
Replace sending of com.snowplowanalytics.com/example context with a real schema in Iglu

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-java-tracker#121]
To prevent problems if the test suite is pointed at a live Snowplow pipeline...

Suggested schema: https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/geolocation_context/jsonschema/1-0-0

**Comment by mscwilson** [comment]
It would be better to use the Snowplow Micro testing pipeline.
