### ISSUE TITLE
Ensure only String values are added to the TrackerPayload

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-java-tracker#127]
Replace with options for numeric types.

**Comment by jbeemster** [comment]
Hey @alexanderdean with this ticket.  What types do we want to allow as Values to be added to the TrackerPayload?

String, Int, Double, Float, Boolean ?

**Comment by alexanderdean** [comment]
Hi @jbeemster - those five types sound good. Does this ticket still make sense to you given other trackers' evolution?

**Comment by jbeemster** [comment]
I have been thinking about TrackerPayloads a bit and I think we can look at it in a few different ways:

Firstly our `payload_data` schema only has strings in it currently so should we really be allowing anything other than Strings to ever enter the Payload?

Secondly do we want to allow developers to use this class as a building block for their SelfDescribingJsons?  If so should be restricting any of their value types at all as it is not really up to us what they put in an `unstructured_event`?

Thirdly is it actually an issue to allow any type to be added? Internally we can ensure that we always add String values to the TrackerPayload so do we really need to limit anything here.

---

My suggestion would be to reduce TrackerPayload to only allow (String, String) pairs to allow us to have better internal type safety with the end payload.  At least until we start to support more types in the `payload_data` schema.  Developers can then use Map<String, Objects> for data in their SelfDescribingJsons.  

Thoughts @alexanderdean ?

**Comment by alexanderdean** [comment]
Sounds good to me! I think a user-exposed Payload class is a hangover from
a pre-SelfDescJson world...
