### ISSUE TITLE
 Add a custom context based on EC2 instance metadata

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-java-tracker#141]
Resources:
- https://github.com/takus/fluent-plugin-ec2-metadata
- https://github.com/dump247/aws-mock-metadata
- https://github.com/femto113/node-ec2-instance-data/blob/master/index.js
- https://github.com/tramzee/ec2-metadata/blob/master/src/io/hivewing/ec2_metadata.clj

**Comment by alexanderdean** [comment]
https://github.com/snowplow/snowplow-scala-tracker/issues/2

**Comment by mscwilson** [comment]
Users can create this functionality themselves using custom contexts. It's not necessary to support it directly in the tracker.
