### ISSUE TITLE
Decouple Subject from Tracker

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-java-tracker#144]
In an environment where many different subjects are involved (e.g. a web server or a RabbitMQ bridge), having a single Subject associated with a Tracker is quite restrictive.

Would be much better if the Subject was tied to the specific event being sent.

**Comment by jbeemster** [comment]
So my thoughts for this one @alexanderdean:

* Optional builder parameter for an event of type Subject; if passed in it will override the Tracker Subject
* If no event subject is passed we try to use the Tracker Subject

Seem fair?

**Comment by alexanderdean** [comment]
Sounds good
