### ISSUE TITLE
Move payload construction and sending into an asynchronous model

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-java-tracker#155]
Currently the whole emitter is synchronous from end to end.  We need to update this model to take advantage of multi-threading and asynchronous sending to improve performance.

See Android-Classic for reference: https://github.com/snowplow/snowplow-android-tracker/tree/master/snowplow-android-tracker-classic/src/main/java/com/snowplowanalytics/snowplow/tracker/classic

**Comment by paulboocock** [comment]
Will be solved in #222
