### ISSUE TITLE
Expand Emitter interface to include getters and setters for all parameters

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-java-tracker#162]
The emitter, once set, is very locked down as it is hidden behind an interface with only one function.  It would be good to:
- Have all parameters for the emitters stored in `BaseEmitter` as protected variables.
- Getters and setters for these variables available in the `Emitter` interface and the `BaseEmitter`.

This allows greater ease of use and much easier testing.

**Comment by alexanderdean** [comment]
Pushing back...

**Comment by mscwilson** [comment]
Doesn't look like this is relevant anymore. Closing!
