### ISSUE TITLE
TrackerPayload logger is verbose on INFO level

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-java-tracker#179]
Reference: https://github.com/snowplow/snowplow/issues/2630

**Comment by jbeemster** [comment]
Relevant line: https://github.com/snowplow/snowplow-java-tracker/blob/master/src/main/java/com/snowplowanalytics/snowplow/tracker/payload/TrackerPayload.java#L49

**Comment by paulboocock** [comment]
This is currently at Logger.Debug.
