### ISSUE TITLE
Add ability to send events via Akka middleware

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-java-tracker#18]
Similar to how the Python Tracker works with Celery, Redis etc. Talk to @fblundun for the Python angle and @alexanderdean for the Akka angle.

http://akka.io/

**Comment by mscwilson** [comment]
This is no longer aligned with our roadmap. It's overkill for this tracker; we're looking into alternative solutions for version 1.0.0. Closing.
