### ISSUE TITLE
Alter logging for invalid keys only when adding to TrackerPayload 

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-java-tracker#186]
https://github.com/snowplow/snowplow/issues/3107

**Comment by jbeemster** [comment]
Hi @reevesm - you are correct this is not really an ERROR.  The TrackerPayload rejects all invalid key-value pairs so that we do not have to individually check each value before adding it to the Payload.

I think that the options here are:

1. Drop the log level to INFO - as it is not an ERROR
2. Remove logging for this entirely

**Comment by reevesm** [comment]
Hi @jbeemster. Either option sounds good to me.

**Comment by skagedal** [comment]
Hi, any updates on this? Kim's fix looks great to me, if it needs to be logged at all.

**Comment by paulboocock** [comment]
Going to take a slightly different path with this one, and that is to only log when an invalid key is added (null or empty keys are not allowed). We don't really know if a value is invalid or not and for some schemas, a null or empty value could be valid.
