### ISSUE TITLE
Java Tracker Failing with Jackson Error

### ISSUE THREAD

**Issue by rahulrsingh09** [snowplow/snowplow-java-tracker#198]
I am getting a weird error when trying to run the Java tracker 

Please Help

```
        HttpClientAdapter adapter = OkHttpClientAdapter.builder()
                .url("http://www.acme.com") // at this line
                .httpClient(client)
                .build();
```

> Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonProcessingException
> 	at com.snowplowanalytics.snowplow.tracker.http.AbstractHttpClientAdapter.<init>(AbstractHttpClientAdapter.java:63)
> 	at com.snowplowanalytics.snowplow.tracker.http.OkHttpClientAdapter.<init>(OkHttpClientAdapter.java:76)
> 	at com.snowplowanalytics.snowplow.tracker.http.OkHttpClientAdapter$Builder.build(OkHttpClientAdapter.java:60)
> 	at com.example.snowplow.App.main(App.java:36)
> Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by BenFradet** [comment]
Hello @rahulrsingh09 , please redirect your support requests to [our Discourse](https://discourse.snowplowanalytics.com/).

**Comment by rahulrsingh09** [comment]
@BenFradet  This is more of a issue because i am following the docs you have mentioned then why have a git issue page

**Comment by BenFradet** [comment]
This is most likely related to another dependency bringing a different version of jackson and as a result is not related to the java tracker.

This github issue tracker is dedicated to things that will result in changes in the code base, not usage problems.

**Comment by rahulrsingh09** [comment]
@BenFradet Thanks will post in Discourse

**Comment by rahulrsingh09** [comment]
@BenFradet Can you please check on this Link no resolution as such https://discourse.snowplowanalytics.com/t/java-tracker-failing-with-jackson-error/1852
