### ISSUE TITLE
Java Tracker failing

### ISSUE THREAD

**Issue by rahulrsingh09** [snowplow/snowplow-java-tracker#199]
I am getting the following issue while trying to run a simple Java Tracker
```

[main] INFO com.snowplowanalytics.snowplow.tracker.payload.TrackerPayload - Adding new kv pair: id->Browse
[main] INFO com.snowplowanalytics.snowplow.tracker.payload.TrackerPayload - Adding new kv pair: name->Home > Browse Folder
[main] INFO com.snowplowanalytics.snowplow.tracker.payload.TrackerPayload - Adding new kv pair: e->ue
[main] INFO com.snowplowanalytics.snowplow.tracker.payload.TrackerPayload - Adding new map: {schema=iglu:com.snowplowanalytics.snowplow/unstruct_event/jsonschema/1-0-0, data={schema=iglu:com.snowplowanalytics.snowplow/screen_view/jsonschema/1-0-0, data={id=Browse, name=Home > Browse Folder}}}
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64String([B)Ljava/lang/String;
	at com.snowplowanalytics.snowplow.tracker.Utils.base64Encode(Utils.java:111)
	at com.snowplowanalytics.snowplow.tracker.payload.TrackerPayload.addMap(TrackerPayload.java:91)
	at com.snowplowanalytics.snowplow.tracker.events.Unstructured.getPayload(Unstructured.java:90)
	at com.snowplowanalytics.snowplow.tracker.Tracker.track(Tracker.java:269)
	at com.snowplowanalytics.snowplow.tracker.Tracker.track(Tracker.java:274)
	at com.example.snowplow.App.main(App.java:57)

Process finished with exit code 1

```

I looked at this issue and i think it is related to some extent as my deps use version .12 

https://github.com/snowplow/snowplow-java-tracker/issues/172

**Comment by BenFradet** [comment]
the tracker is using 1.10, which version are you using?

**Comment by rahulrsingh09** [comment]
By default it is pointing to 1.2 . I guess that is the issue  . I am using the snowplow java tracker jar that internally resolves deps

**Comment by rahulrsingh09** [comment]
I can safely say that it is an issue with the maven pom file that you are using internally with the snowplow java tracker jar as it downloads the version 12 where as i  think it is compatible with version 10.  you might need to revist #172

**Comment by BenFradet** [comment]
how so? the dependencies are against 1.10: https://github.com/snowplow/snowplow-java-tracker/blob/develop/build.gradle#L61

**Comment by chuwy** [comment]
I think if problem is only in Base64, then it is safer to bump minimal required JRE to JRE8, use standard `java.util.Base64` and get rid of commons codec at all in the next release.

**Comment by chuwy** [comment]
Wiki page is actually misleading. Latest version is 0.8.2, not 0.8.0. @rahulrsingh09 did you use one mentioned in wiki (0.8.0)?

**Comment by rahulrsingh09** [comment]
yes i used the one in wiki @chuwy  . can you point to the latest version

**Comment by chuwy** [comment]
@rahulrsingh09 just fixed wiki page, please use updated links.

**Comment by chuwy** [comment]
I'm sure this is going to fix the problem. Closing.
