### ISSUE TITLE
Java Tracker not Terminating the thread after successfully sending Events 

### ISSUE THREAD

**Issue by rahulrsingh09** [snowplow/snowplow-java-tracker#200]
The Trackers continues to run even after the event has been send , Have to manually use  `System.exit(1) `to terminate the process which is not clean

**Comment by chuwy** [comment]
Hey, @rahulrsingh09, I think this was due running `Emitter` thread. `BatchEmitter` supports `close()` method that is supposed to shut down the thread. Did you try to use it in shutdown hook?
