### ISSUE TITLE
Update all non-static Loggers to static

### ISSUE THREAD

**Issue by bbplanon** [snowplow/snowplow-java-tracker#213]
The loggers in the SelfDescribingJson, TrackerPayload, ApacheHttpClientAdapter and OkHttpClientAdapter class are not static. This means that every instance of these classes instantiate a new logger object. This causes some 
Logger objects are often declared static in other projects, which is also the case in the other classes of the Tracker which contain a Logger object (SimpleEmitter and BatchEmitter).
The SimpleEmitter and BatchEmiiter are only created once, where objects of the SelfDescribingJson or TrackerPayload are created very often when building an event. Therefore, the overall performance of the Tracker would increase if static loggers would be used in these classes.

I would suggest changing:
```java
private final Logger LOGGER = LoggerFactory.getLogger(SelfDescribingJson.class);
```

to something like:
```java
private static final Logger LOGGER = LoggerFactory.getLogger(SelfDescribingJson.class);
```

**Comment by paulboocock** [comment]
Seems like a sensible change to me.
