### ISSUE TITLE
Create Schema annotation for self-describing unstruct events / contexts

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-java-tracker#27]
The basic idea is that you would annotate a Java class like this:

``` java
@Schema(vendor = "com.atari.pacman", name = "gameLevel", format = "jsonschema", version = "1-0-0") // Maps the bean to our self-describing schema for the game level
public class GameLevel implements Serializable {
  ...
}
```

and then it's easy to add it in as a context to an event. When an annotated class is passed in as a context (or an unstructured event) then it is automatically converted into a self-describing JSON.

**Comment by alexanderdean** [comment]
This is quite ambitious - interested to see if it is doable...

**Comment by mscwilson** [comment]
This idea will be superseded by our new plans, in discussion, for schema/class generation.
