### ISSUE TITLE
Update all copyright notices

### ISSUE THREAD

**Issue by AlexBenny** [snowplow/snowplow-java-tracker#279]
The Copyright Notice at the bottom of the [LICENSE file](https://github.com/snowplow/snowplow-java-tracker/blob/73cd5a496212fd38771c3f0d64a9ecba92f490e2/LICENSE-2.0.txt#L190
) is missing. It should look something like this: https://github.com/snowplow/snowplow-gtm-server-side-client/blob/main/LICENSE#L189

Also, we should update all the copyright headers (in source files):
` * Copyright (c) 2014-2020 Snowplow Analytics Ltd. All rights reserved.`
To:
` * Copyright (c) 2014-2021 Snowplow Analytics Ltd. All rights reserved.`

**Comment by paulboocock** [comment]
It should also be `LICENSE` rather than `LICENSE-2.0.txt` so that it is properly identified by Github.
