### ISSUE TITLE
Return eventId from Tracker.track()

### ISSUE THREAD

**Issue by mscwilson** [snowplow/snowplow-java-tracker#304]
The event ID (a UUID string) is generated when an Event object is created. We also currently provide the option for the user to override this and manually set an event ID.

This is risky and could result in events not having unique IDs. This functionality should be deprecated.

**Comment by mscwilson** [comment]
It's also possible to manually set the - i.e. override the autogenerated - `deviceCreatedTimestamp`. But `trueTimestamp` is provided for manual timestamp setting already? Should users be able to set `dtm`?

**Comment by paulboocock** [comment]
It should not be possible to manually set the `deviceCreatedTimestamp`, this should come from the system clock. True Timestamp is available if a custom timestamp needs to be provided.

**Comment by mscwilson** [comment]
I've changed the title of this issue to reflect the more interesting part of the changes I've made in PR #310.
