### ISSUE TITLE
Remove Guava dependency

### ISSUE THREAD

**Issue by LeoNiedermeier** [snowplow/snowplow-java-tracker#320]
**Is your feature request related to a problem? Please describe.**

The library includes guava, but uses just two classes (so far I can see)
* Precondition
* ImmutableMap

Both can be replaced with plain java classes, e.g
* Precondition => java.util.Objects#requireXYZ methods

**Describe the solution you'd like**

No guava dependency because
* you use just few classes from guava which can replcaed by core java classes
* version conflicts, because other dependencies in a application which uses snowplow can also include guava with different version
* as user of this library i do not want additional transitive dependencies in my application

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by mscwilson** [comment]
Hi @LeoNiedermeier. We just released Java tracker v1. Guava has been removed 😊
