### ISSUE TITLE
Add Kafka backing for tracker

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-java-tracker#54]
See also: #8

**Comment by aragnon** [comment]
@alexanderdean What is the status of the Kafka backend? It seems rather odd that you talked about a Kafka backend over a year ago on various social media and that nothing appears to have happened on this front.

**Comment by alexanderdean** [comment]
Hey @aragnon! Yes, we're still planning a Kafka implementation for Snowplow - we hope to get some time next year to spend on this. Are you interested in working on it?

**Comment by ssheikholeslami** [comment]
Hi, I was wondering to know what's the current status of Kafka sink for Scala Collector? Do you plan to add it soon? We're thinking of switching to Snowplow for our data pipeline, but using Kinesis is not an option for us. I noticed there has been ongoing work on[#981](https://github.com/snowplow/snowplow/pull/981) for some time.
We're also ready to implement this feature.
@fnozarian

**Comment by alexanderdean** [comment]
Hey @ssheikholeslami - yes we are still planning to release this. We hope to get out an RFC on Discourse discussing the plan for Kafka support soon. Are you keen to work on this feature?

**Comment by ssheikholeslami** [comment]
Absolutely, and it would really help if you could point me to some material for starting up fast.
I've already created an account on Discourse.

**Comment by ssheikholeslami** [comment]
@alexanderdean I'm actually waiting for an update from your side :D

**Comment by mscwilson** [comment]
This isn't part of the roadmap any more. 

The [Snowplow collector](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/stream-collector/), however, does work with Kafka. As can [Stream Enrich](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/enrichment-components/stream-enrich/).
